
- name: Generate Semaphore Service System Unit
  template:
    src: systemd_unit.j2
    dest: /etc/systemd/system/semaphore.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start semaphore service
  ansible.builtin.systemd:
    name: semaphore
    state: started
    enabled: yes  # Если нужно, чтобы сервис запускался при старте системы
      
- name: "Wait until Semaphore Service started"
  wait_for:
    host: "{{ ansible_host }}"
    port: 3000
    timeout: 120

- name: Check status of semaphore service
  ansible.builtin.systemd:
    name: semaphore
    state: started
  register: semaphore_status

- name: Print the status of the semaphore service
  debug:
    var: semaphore_status
