---

- name: Generate Semaphore Service System Unit
  template:
    src: semaphore.conf.j2
    dest: /etc/nginx/conf.d/semaphore.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - "Restart NGINX"

- name: Remove default config file /etc/nginx/conf.d/default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - "Restart NGINX"

- name: Generate Semaphore Service System Unit
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - "Restart NGINX"
